<template>
  <div>
    <Scroll class="content">
      <ul>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
        <li>个人</li>
      </ul>
    </Scroll>
  </div>
</template>

<script>
import Scroll from "components/common/scroll/Scroll";
export default {
  components: {
    Scroll,
  },
};
</script>

<style scoped>
.content {
  height: 300px;
  background: red;
  overflow: hidden;
}
</style>